// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO4dQ2Nn7-G7RQbN7QcAR7zS4NrdYkyg0',
    appId: '1:870355236952:web:5c837fde65ff5cde10f22d',
    messagingSenderId: '870355236952',
    projectId: 'bystander-e19c0',
    authDomain: 'bystander-e19c0.firebaseapp.com',
    storageBucket: 'bystander-e19c0.firebasestorage.app',
    measurementId: 'G-RM3NVFG0P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPFovWthk4n7jVTtrhAlXVK0zKOFzZJN8',
    appId: '1:870355236952:android:1e463491dbf8e4f910f22d',
    messagingSenderId: '870355236952',
    projectId: 'bystander-e19c0',
    storageBucket: 'bystander-e19c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNxGhAa-3ttibK_o7MxCtT9xVM_ODchAI',
    appId: '1:870355236952:ios:695446dc43627fe110f22d',
    messagingSenderId: '870355236952',
    projectId: 'bystander-e19c0',
    storageBucket: 'bystander-e19c0.firebasestorage.app',
    iosClientId: '870355236952-huhv167ckjp3ftufqorcaqd4to25pf4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.bystanderFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNxGhAa-3ttibK_o7MxCtT9xVM_ODchAI',
    appId: '1:870355236952:ios:695446dc43627fe110f22d',
    messagingSenderId: '870355236952',
    projectId: 'bystander-e19c0',
    storageBucket: 'bystander-e19c0.firebasestorage.app',
    iosClientId: '870355236952-huhv167ckjp3ftufqorcaqd4to25pf4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.bystanderFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO4dQ2Nn7-G7RQbN7QcAR7zS4NrdYkyg0',
    appId: '1:870355236952:web:a8ce842288d4de3110f22d',
    messagingSenderId: '870355236952',
    projectId: 'bystander-e19c0',
    authDomain: 'bystander-e19c0.firebaseapp.com',
    storageBucket: 'bystander-e19c0.firebasestorage.app',
    measurementId: 'G-573RFPHBFF',
  );
}
